# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


# Bit-exact regression gate for the default Float64 CPU path.
#
# The "Reproducibility" testset in runtests.jl compares against stored values
# with rtol=eps(Float32(L/2))≈3e-5, which cannot tell a bit-identical result
# from a merely re-associated one. Generalising the element type must not change
# the Float64 numbers at all, so this gate asserts `==`.
#
# The cases cover both `pk` dispatch families, because they take completely
# different routes through scale_by_pk!(): a callable goes through pk_to_pkG()
# and multiply_by_pkG!(), while an array goes through the multipole expansion
# and a 3D FFT.
#
# After an intentional numerical change, regenerate the references with
#
#     LNG_REGEN_REFERENCE=1 julia --project -e 'using Pkg; Pkg.test(test_args=["reproducibility"])'
#
# and overwrite test/reproducibility_reference.jl with the printed block.

using Test
using LogNormalGalaxies
using StableRNGs


# The rng is created fresh per case: task creation also draws from the global
# RNG, so results would otherwise depend on the task-creation scheme.
const REPRO_SEED = 981670238674


function reproducibility_cases()
    nbar = 1e-8
    L = 1e3
    nmesh = 32
    bias = 1.5

    keq = 2e-2
    c = 3 * keq^4
    a = 2e4 * 4 * keq^3
    pkfn(k) = a * k / (c + k^4)

    common = (; nmesh, bias, voxel_window_power=1, velocity_assignment=0, sigma_psi=0)

    cases = Pair{String,Function}[]

    for rsd in (false, true), vwc in (0, 1)
        name = "callable rsd=$rsd vwc=$vwc"
        push!(cases, name => () -> simulate_galaxies(nbar, L, pkfn; common...,
                f=rsd, rng=StableRNG(REPRO_SEED), voxel_window_correction=vwc))
    end

    # Tabulated pk. The first dimension must be at least √3*(nmesh÷2+1)≈30 so
    # that the corners of the box can be filled.
    kin = (2π / L) .* (0:(nmesh - 1))
    pkmono = pkfn.(kin)
    pk1d = pkmono
    pk2d = [pkmono zero(pkmono) 0.1 .* pkmono]  # ell = 0, 1, 2

    push!(cases, "pk1d" => () -> simulate_galaxies(nbar, L, pk1d; common...,
            f=true, rng=StableRNG(REPRO_SEED)))
    push!(cases, "pk2d" => () -> simulate_galaxies(nbar, L, pk2d; common...,
            f=true, rng=StableRNG(REPRO_SEED)))

    fog = (; common..., sigma_psi=3.0)  # the later entry wins over the splat
    push!(cases, "callable rsd=true vwc=0 sigma_psi" => () -> simulate_galaxies(nbar, L, pkfn;
            fog..., f=true, rng=StableRNG(REPRO_SEED), voxel_window_correction=0))

    return cases
end


function regenerate_reproducibility_reference(cases)
    # simulate_galaxies() is chatty, so collect everything before printing the
    # block: otherwise its @time/@show output interleaves into the literals.
    results = redirect_stdout(devnull) do
        [name => run() for (name, run) in cases]
    end

    println()
    println("#### BEGIN test/reproducibility_reference.jl ####")
    println("# Generated by test/reproducibility.jl with LNG_REGEN_REFERENCE=1.")
    println("# Do not edit by hand; see the header of test/reproducibility.jl.")
    println()
    println("const REPRODUCIBILITY_REFERENCE = Dict{String,Tuple{Matrix{Float64},Matrix{Float64}}}(")
    for (name, (x⃗, Ψ)) in results
        println("    ", repr(name), " => (")
        println("        ", repr(x⃗), ",")
        println("        ", repr(Ψ), ",")
        println("    ),")
    end
    println(")")
    println("#### END test/reproducibility_reference.jl ####")
    println()
end


@testset "reproducibility (bit-exact)" begin
    cases = reproducibility_cases()

    if get(ENV, "LNG_REGEN_REFERENCE", "0") == "1"
        regenerate_reproducibility_reference(cases)
        @test_skip "references regenerated, not compared"
    else
        include("reproducibility_reference.jl")

        @testset "$name" for (name, run) in cases
            x⃗, Ψ = run()

            @test all(isfinite, x⃗)
            @test all(isfinite, Ψ)

            x⃗ref, Ψref = REPRODUCIBILITY_REFERENCE[name]

            # `==`, not `≈`: this gate exists to detect any change in the bits.
            @test size(x⃗) == size(x⃗ref)
            @test size(Ψ) == size(Ψref)
            @test x⃗ == x⃗ref
            @test Ψ == Ψref
        end
    end
end


# vim: set sw=4 et sts=4 :
