# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.


# Regression gate for the default Float64 CPU path.
#
# Two gates in one. On the machine that recorded the references
# (REPRODUCIBILITY_MACHINE in the reference file) it is bit-exact: generalising
# the element type must not change the Float64 numbers at all, and `≈` cannot
# tell a bit-identical result from a merely re-associated one. Anywhere else --
# CI is x86_64-Linux, the references are aarch64-Darwin -- FFTW may pick other
# codelets and libm rounds differently, so Ψ drifts by a few ulps: there the
# `==` assertions skip and the tight `≈` ones are the gate. The measured
# relative difference is reported either way.
#
# x⃗ is exact on any IEEE machine: a position is (index - 0.5 + rand(rng) - 0.5)
# * Δx, pure StableRNG and grid arithmetic. The only thing that can move it is
# a pois_rand() acceptance flipping, and that shows up as a size mismatch, not
# as a small difference.
#
# The cases cover both `pk` dispatch families, because they take completely
# different routes through scale_by_pk!(): a callable goes through pk_to_pkG()
# and multiply_by_pkG!(), while an array goes through the multipole expansion
# and a 3D FFT.
#
# After an intentional numerical change -- or a Julia upgrade on the recording
# machine, which also perturbs Ψ -- regenerate the references with
#
#     LNG_REGEN_REFERENCE=1 julia --project -e 'using Pkg; Pkg.test(test_args=["reproducibility"])'
#
# and overwrite test/reproducibility_reference.jl with the printed block,
# keeping its licence header. LNG_REPRO_MACHINE exercises the foreign-machine
# path from the recording machine.

using Test
using LogNormalGalaxies
using StableRNGs

isdefined(@__MODULE__, :reldiff) || include("testutils.jl")


# The rng is created fresh per case: task creation also draws from the global
# RNG, so results would otherwise depend on the task-creation scheme.
const REPRO_SEED = 981670238674


# Sys.MACHINE would do, except that it embeds the macOS point release, so every
# OS update would switch the bit-exact gate off without saying so. Arch and
# kernel are what actually select the FFTW codelets and libm.
repro_machine() = get(ENV, "LNG_REPRO_MACHINE", "$(Sys.ARCH)-$(Sys.KERNEL)")


# x⃗ is exact everywhere, so its tolerance only has to be non-zero. Ψ comes out
# of the FFTs; perturbing pk by one ulp moves it by ~5e-16 relative in all six
# cases, and pk_to_pkG()'s adaptive quadrature is the only thing that could
# plausibly do worse. Both are orders of magnitude below the re-association
# this gate exists to catch, which lands at 1e-15 and up.
const REPRO_RTOL_X = 1e-13
const REPRO_RTOL_Ψ = 1e-10


function reproducibility_cases()
    nbar = 1e-8
    L = 1e3
    nmesh = 32
    bias = 1.5

    keq = 2e-2
    c = 3 * keq^4
    a = 2e4 * 4 * keq^3
    pkfn(k) = a * k / (c + k^4)

    common = (; nmesh, bias, voxel_window_power=1, velocity_assignment=0, sigma_psi=0)

    cases = Pair{String,Function}[]

    for rsd in (false, true), vwc in (0, 1)
        name = "callable rsd=$rsd vwc=$vwc"
        push!(cases, name => () -> simulate_galaxies(nbar, L, pkfn; common...,
                f=rsd, rng=StableRNG(REPRO_SEED), voxel_window_correction=vwc))
    end

    # Tabulated pk. The first dimension must be at least √3*(nmesh÷2+1)≈30 so
    # that the corners of the box can be filled.
    kin = (2π / L) .* (0:(nmesh - 1))
    pkmono = pkfn.(kin)
    pk1d = pkmono
    pk2d = [pkmono zero(pkmono) 0.1 .* pkmono]  # ell = 0, 1, 2

    push!(cases, "pk1d" => () -> simulate_galaxies(nbar, L, pk1d; common...,
            f=true, rng=StableRNG(REPRO_SEED)))
    push!(cases, "pk2d" => () -> simulate_galaxies(nbar, L, pk2d; common...,
            f=true, rng=StableRNG(REPRO_SEED)))

    return cases
end


function regenerate_reproducibility_reference(cases)
    # simulate_galaxies() is chatty, so collect everything before printing the
    # block: otherwise its @time/@show output interleaves into the literals.
    results = redirect_stdout(devnull) do
        [name => run() for (name, run) in cases]
    end

    println()
    println("#### BEGIN test/reproducibility_reference.jl ####")
    println("# Generated by test/reproducibility.jl with LNG_REGEN_REFERENCE=1.")
    println("# Do not edit by hand; see the header of test/reproducibility.jl.")
    println()
    println("# Recorded with Julia ", VERSION, ". The `==` assertions run only here.")
    println("const REPRODUCIBILITY_MACHINE = ", repr(repro_machine()))
    println()
    println("const REPRODUCIBILITY_REFERENCE = Dict{String,Tuple{Matrix{Float64},Matrix{Float64}}}(")
    for (name, (x⃗, Ψ)) in results
        println("    ", repr(name), " => (")
        println("        ", repr(x⃗), ",")
        println("        ", repr(Ψ), ",")
        println("    ),")
    end
    println(")")
    println("#### END test/reproducibility_reference.jl ####")
    println()
end


@testset "reproducibility" begin
    cases = reproducibility_cases()

    if get(ENV, "LNG_REGEN_REFERENCE", "0") == "1"
        regenerate_reproducibility_reference(cases)
        @test_skip "references regenerated, not compared"
    else
        include("reproducibility_reference.jl")

        @testset "$name" for (name, run) in cases
            x⃗, Ψ = run()

            @test all(isfinite, x⃗)
            @test all(isfinite, Ψ)

            x⃗ref, Ψref = REPRODUCIBILITY_REFERENCE[name]

            # `≈` and reldiff() both broadcast, so a differently sized result
            # throws DimensionMismatch instead of failing. Stop after the size
            # test, which is the informative one anyway.
            @test size(x⃗) == size(x⃗ref)
            @test size(Ψ) == size(Ψref)
            size(x⃗) == size(x⃗ref) && size(Ψ) == size(Ψref) || continue

            err_x = reldiff(x⃗ref, x⃗)
            err_Ψ = iszero(Ψref) ? norm(Ψ) : reldiff(Ψref, Ψ)  # f=false has Ψ≡0
            @info "reproducibility: $name" err_x err_Ψ

            @test x⃗ ≈ x⃗ref rtol=REPRO_RTOL_X
            @test Ψ ≈ Ψref rtol=REPRO_RTOL_Ψ

            # The bits only reproduce where they were recorded.
            foreign = repro_machine() != REPRODUCIBILITY_MACHINE
            @test x⃗ == x⃗ref skip=foreign
            @test Ψ == Ψref skip=foreign
        end
    end
end


# vim: set sw=4 et sts=4 :
